### ISSUE TITLE
How was BERT evaluated? (expt setup)

### ISSUE THREAD

**Issue by Axe--** [keeeeenw/MicroLlama#2]

**Comment by keeeeenw** [comment]
I used this exact command for evaluation. 
https://github.com/keeeeenw/lm-evaluation-harness/blob/34a5c9efebdb771d70659c75c96e1c083e634f29/eval.sh#L25

**Comment by Axe--** [comment]
Gotcha, what about finetuning BERT for this expt? (assuming no few-shot eval)

**Comment by keeeeenw** [comment]
I have not tried finetuning BERT. For apple to apple comparison, I used the settings for evaluating both my model and the BERT base model without any finetuning.

**Comment by Axe--** [comment]
Ah! Got it. Had never explored zero-shot with BERT. 
Thanks!
